name: "mnist"
exp_name: "test"

unet:
  model: "AE_CNN_bottleneck"
  in_channels: 1

scheduler:
  start: 1e-4
  end: 2e-2
  schedule: linear
  n_timestep: 1000
  variance_type: "fixed_large"

data:
  dataset: "mnist_gaussian_200"
  dataset_dir: "/scratch/yufan/nn_diff/gen_param_2_gen_param_2/"
  augmentation_scale: 0.001

learning_rate: 1e-4
scale_lr: False
train_batch_size: 4
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.0
adam_eps: 1e-8
lr_scheduler: "constant"
lr_warmup_steps

num_training_steps: 1000

mixed_precision: "fp16"
gradient_accumulation_steps: 1
max_grad_norm: 1.0

num_workers: 4

seed: 3407